export const GET_ALL_GOODS = 'GET_ALL_GOODS';
export const GET_ALL_GOODS_SUCCESS = 'GET_ALL_GOODS_SUCCESS';
export const GET_ALL_GOODS_FAIREU = 'GET_ALL_GOODS_FAIURE';

export const ADD_GOOD = 'ADD_GOOD';
export const ADD_GOOD_SUCCESS = 'ADD_GOOD_SUCCESS';
export const ADD_GOOD_FAIURE = 'ADD_GOOD_FAIURE';